version: "3.8"
services:
  courier_tracking:
    image: dpikilidis/courier-tracking-bot:latest
    container_name: courier-tracking-bot
    restart: always
    volumes:
      - ./logs:/logs
      - ./data:/data
    environment:
      - LOG_NAME=courier-tracking-bot
      - LOG_LEVEL=INFO
      - TRACKER_URL=https://courier-api.danielpikilidis.com
      - DISCORD_KEY= # KEY HERE