services:
  bot:
    image: dpikilidis/courier-tracking-bot:latest
    container_name: courier-tracking-bot
    volumes:
      - ./logs:/logs
      - ./data:/data
    environment:
      - LOG_NAME=courier-tracking-bot
      - LOG_LEVEL=INFO
      - TRACKER_URL=https://courier-api.danielpikilidis.com
      - DISCORD_KEY= # KEY HERE
    restart: unless-stopped
